//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JapaneWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyPost
    {
        public int IdStudyPost { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public string Img { get; set; }
        public string Detail { get; set; }
        public string N { get; set; }
        public Nullable<int> IdThemePost { get; set; }
    
        public virtual Level Level { get; set; }
        public virtual ThemeOfPost ThemeOfPost { get; set; }
    }
}
