//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JapaneWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Volcabulary
    {
        public int IdVol { get; set; }
        public string Kanji { get; set; }
        public string Furigana { get; set; }
        public string Meaning { get; set; }
        public string N { get; set; }
    
        public virtual Level Level { get; set; }
    }
}
